### ISSUE TITLE
建议增加 `rustfmt` 和 `rust-toolchain` 相关配置文件

### ISSUE THREAD

**Issue by mlycore** [Tongsuo-Project/RustyVault#14]
如题，通过增加 `rust-toolchain` 文件指定工具链版本，以及通过 `rustfmt.toml` 提供代码风格检查。这样可以帮助其他开发者快速上手项目。

rust-toolchain 示例：

```
nightly-2022-12-15
```

rustfmt.toml 示例：

```toml
edition = "2021"

condense_wildcard_suffixes = true
group_imports = "StdExternalCrate"
imports_granularity = "Crate"
license_template_path = "etc/license.template"
newline_style = "Unix"
reorder_imports = true
report_fixme = "Unnumbered"
trailing_comma = "Vertical"
use_field_init_shorthand = true
use_small_heuristics = "Max"
merge_derives = false
comment_width = 120
```
